name: Deploy to Vercel Microfrontends

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./host
        run: npm install

      - name: Run tests for host
        working-directory: ./host
        run: npm test

  deploy-host:
    runs-on: ubuntu-latest
    needs: test-host
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy host to Vercel
        working-directory: ./host
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  test-app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./app1
        run: npm install

      - name: Run tests for app1
        working-directory: ./app1
        run: npm test

  deploy-app1:
    runs-on: ubuntu-latest
    needs: test-app1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app1 to Vercel
        working-directory: ./app1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  test-app2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./app2
        run: npm install

      - name: Run tests for app2
        working-directory: ./app2
        run: npm test

  deploy-app2:
    runs-on: ubuntu-latest
    needs: test-app2
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app2 to Vercel
        working-directory: ./app2
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

  test-app3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./app3
        run: npm install

      - name: Run tests for app3
        working-directory: ./app3
        run: npm test

  deploy-app3:
    runs-on: ubuntu-latest
    needs: test-app3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app3 to Vercel
        working-directory: ./app3
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
