name: Deploy to Vercel Microfrontends

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy host to Vercel
        working-directory: ./microfrontend-pokemonapp/host
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm

  deploy-app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app1 to Vercel
        working-directory: ./microfrontend-pokemonapp/app1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm

  deploy-app2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app2 to Vercel
        working-directory: ./microfrontend-pokemonapp/app2
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm

  deploy-app3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy app3 to Vercel
        working-directory: ./microfrontend-pokemonapp/app3
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
